[phases.setup]
nixPkgs = ["nodejs", "npm", "php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public server.php"
